name: Run Tests

on:
  [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install .
    - name: Test with pytest
      run:
        pytest -sv test_brewing/test_brewing.py

